<?php
/**
 * Like details for admin sidebar.
 *
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var int $totalLikes
 * @var int $totalDislikes
 * @var int $totalVotes
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
?>

<div class="meta-group">
    <h4><?= $escape($translate('Likes')) ?></h4>
    <div class="value">
        <div class="like-stats">
            <span class="stat likes">
                <span class="fa fa-thumbs-up"></span>
                <?= (int) $totalLikes ?>
            </span>
            /
            <span class="stat dislikes">
                <span class="fa fa-thumbs-down"></span>
                <?= (int) $totalDislikes ?>
            </span>
            =
            <span class="stat total">
                <?= $escape(sprintf($translate('(%d total votes)'), $totalVotes)) ?>
            </span>
        </div>
    </div>
</div>
