<?php
/**
 * Like details for admin sidebar and browse details.
 *
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
?>

<div class="meta-group">
    <h4><?= $escape($translate('Likes')) ?></h4>
    <div class="value">
        <?= $this->🖒($resource) ?>
    </div>
</div>
